name: mobiwoom
description: Mobiwoom

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 7.0.3+80012

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  responsive_builder: 0.3.0
  provider: ^4.3.2+3
  intl: ^0.16.1
  dio: ^3.0.10
  rxdart: 0.24.0
  crypto: ^2.1.5
  get_it: ^5.0.3
  bot_toast: ^2.4.0
  shared_preferences: ^0.5.12+4
  sqflite: ^1.3.2+1
  floor: 0.18.0
  modal_progress_hud: ^0.1.3
  package_info: ^0.4.3
  credit_card: ^0.1.8
  flutter_google_places: 0.2.6
  google_maps_webservice: ^0.0.18
  expressions: ^0.1.5
  timezone: ^0.5.6
  geolocator: ^6.2.1
  google_maps_flutter: ^0.5.33
  google_maps_flutter_web: ^0.1.0
  url_launcher: ^5.7.10
  fluster: ^1.1.2
  custom_splash: ^0.0.2
  firebase_core: ^0.5.3
  firebase_messaging: ^7.0.3
  firebase_database: ^4.4.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: 1.0.0
  google_fonts: ^1.1.1
  local_auth: ^0.6.3+4
  flutter_secure_storage: ^3.3.5
  language_pickers: ^0.2.0+1
  country_pickers: 1.3.0
  country_code_picker: ^1.7.0
  intro_views_flutter: ^2.9.0
  flag: ^3.1.0
  system_settings: 1.0.1
  infinite_scroll_pagination: ^2.3.0
  upgrader: ^2.8.2
  flutter_phoenix: ^0.1.0
  #firebase_cloud_messaging_interop: ^2.0.1
  wordpress_api: 0.2.1+1
  flutter_html: ^1.2.0
  webview_flutter: ^1.0.7
  #webviewx: ^0.0.4
  #firebase: ^8.0.0
  xml_parser: ^0.1.2
  xml2json: ^4.4.0
  pointer_interceptor: ^0.8.0+2
  pedantic: ^1.9.2
  uuid: ^2.2.2
  meta: ^1.2.2
  path: ^1.7.0
  month_picker_dialog: ^0.3.3
dev_dependencies:
  flutter_launcher_icons: "0.8.1"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images/mapicons/
    - i18n/
    - assets/
    - assets/png/
    - assets/svg/

  fonts:
    - family:  Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
    - family: RobotoCondensed
      fonts:
        - asset: fonts/RobotoCondensed-Regular.ttf
        - asset: fonts/RobotoCondensed-Italic.ttf
          style: italic
        - asset: fonts/RobotoCondensed-Light.ttf
          weight: 200
        - asset: fonts/RobotoCondensed-Bold.ttf
          weight: 700

    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Bold.ttf
          weight: 800
        - asset: fonts/Raleway-Light.ttf


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
